### ISSUE TITLE
Support referencing algorithm steps

### ISSUE THREAD

**Issue by bakkot** [tc39/ecmarkup#192] opened 2020-04-26 16:06 UTC
Currently [emu-xref](https://tc39.es/ecmarkup/#emu-xref) allows linking to specific algorithms, but sometimes (especially in Annex B) we want to talk about specific steps of those algorithms. There's no way to do that automatically, which means we write out step numbers, and those inevitably get stale. It would be good if there were some way to give names to certain algorithm steps and then refer to those names and have that be translated to the appropriate step number.

**Comment by ExE-Boss** [comment] 2020-05-31 07:36
Duplicate of <https://github.com/tc39/ecmarkdown/issues/56>

**Comment by ExE-Boss** [comment] 2020-05-31 07:37
See also: <https://github.com/tc39/ecmarkdown/issues/56>.

**Closed** 2020-06-17 06:51 UTC
